FROM runpod/base:0.6.2-cuda12.4.1

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN python3.11 -m pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .

# Install RunPod
RUN python3.11 -m pip install runpod

# Change CMD to use handler with Python 3.11
CMD ["python3.11", "-u", "rp_handler.py"]